name: Test-API-newman
on:
  schedule: #Execução agendada de segunda a sexta de 6 em 6 horas
  - cron: "0 12 * 2 3"
  
  push:  #Execução por atualização do github na branch main
    branches:
     - 'main'
      
  workflow_dispatch:  #Execução manual
      
      
jobs:
 teste-1:
    
    runs-on: ubuntu-latest
    steps:
      # Faz check-out do seu repositório em $GITHUB_WORKSPACE, para que seu trabalho possa acessá-lo

      - uses: actions/checkout@v4
  
 test:
    name: teste-2
  
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   

    

      # Instalar o node
      - name: Install Node
        uses: actions/setup-node@v4
       


      # Instale o utilitário de linha de comando newman e também instale o html extra reporter

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      # Crie um diretório para carregar os resultados do teste

      - name: Make Directory for results
        run: mkdir -p testResults


      # Execute a coleção POSTMAN

      - name: Run POSTMAN collection on real time
        run: |
          newman run testes_hoje.json -e workspace.postman_globals.json
      
      - name: Run POSTMAN collection
        run: |
          newman run testes_hoje.json -e workspace.postman_globals.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: testResults
